Create publish.yml
I have used the documentation (https://quarto.org/docs/publishing/quarto-pub.html#github-action) to create the publish.yml file. Will need to get the Quarto Pub credentials.

I'm unable to test on my local machine using this command as I keep getting this error for quarto publish quarto-pub:

ERROR: MissingEnvVarsError: The following variables were defined in the example file but are not present in the environment:
  SECRET_KEY, BASE_URL, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME, RESEND_API_KEY

Make sure to add them to your env file.

If you expect any of these variables to be empty, you can set the allowEmptyValues option to true.

Stack trace:
  SECRET_KEY, BASE_URL, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME, RESEND_API_KEY

Make sure to add them to your env file.

If you expect any of these variables to be empty, you can set the allowEmptyValues option to true.
    at assertSafe (file:///opt/quarto/bin/quarto.js:26186:15)
    at load3 (file:///opt/quarto/bin/quarto.js:26147:9)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async dotenvQuartoProfile (file:///opt/quarto/bin/quarto.js:26288:18)
    at async initializeProfileConfig (file:///opt/quarto/bin/quarto.js:26353:46)
    at async projectContext (file:///opt/quarto/bin/quarto.js:73559:29)
    at async createPublishOptions (file:///opt/quarto/bin/quarto.js:109627:21)
    at async publishAction (file:///opt/quarto/bin/quarto.js:109548:28)
    at async Command.actionHandler (file:///opt/quarto/bin/quarto.js:109543:9)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8017:13)